title: Carlos Yanez Santibanez
baseURL: https://www.carlosyanez.id.au
languageCode: en-au
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
markup:
  goldmark:
    renderer:
      unsafe: true
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/carlosyanez
    - name: mastodon
      url: https://fosstodon.org/@carlosyanez
    - name: linkedin
      url: https://www.linkedin.com/in/carlosyanez/
    - name: github
      url: https://github.com/carlosyanez
  author: 'Carlos Yanez Santibanez'
  background_color_class: bg-black
  description: Personal Website
  favicon: ''
  recent_posts_number: 1
  site_logo: ''
  text_color: ''
menu:
  main:
  - name: Home
    pageRef: /
    weight: 10
  - name: About Me
    pageRef: /about
    weight: 20
  - name: Packages
    pageRef: /packages
    weight: 30
  - name: Projects
    url: https://carlosyanez.github.io/projects/index.html
    weight: 40
  - name: Links
    pageref: /links
    weight: 50
